export default {
    about: {
        title: 'About me',
        image: {
            portrait: ''
        },
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit, ex sed auctor vehicula, nulla odio malesuada felis, vel efficitur arcu magna at ex. Donec elementum est odio. Nullam consectetur, nunc eu molestie bibendum, augue arcu congue nunc, non mollis lorem erat sed libero. Sed vitae dictum est. Etiam eu varius lectus, eu auctor justo. Duis eget massa lectus. Ut convallis sagittis vestibulum. Pellentesque euismod purus eget tortor rutrum, at maximus quam egestas. Pellentesque ultrices massa sit amet rhoncus molestie. Integer condimentum erat ut tortor iaculis consectetur. Duis vitae elit id tortor vehicula luctus. Maecenas ultricies neque eget quam tempor bibendum. Praesent tempus viverra dolor non convallis. Aliquam auctor eget mauris at ornare.',
    },
    blog: {
        title: 'Blog',
        entries: [
            {
                id: '',
                date: '',
                title: '',
                image: {
                    headerImg: '',
                    gallery: [
                        {
                            image: {
                                thumbnail: '',
                                big: '',
                            }
                        }
                    ]
                }
            }
        ]
    },
    shop: {
        title: 'Shop',
    },
    contact: {
        title: 'Contact me'
    },
    faq: {
        title: 'Faqs',
        qAndA: [
            {
                q: 'What is Marisa Rivera Art?',
                a: '',
            },
            {
                q: 'Who makes your products?',
                a: '',
            },
            {
                q: 'Who takes your photos?',
                a: '',
            },
            {
                q: 'How do I care for my art?',
                a: '',
            },
            {
                q: 'How long is it going to take to receive my order?',
                a: '',
            },
            {
                q: 'Do you do custom orders?',
                a: '',
            },
        ]
    },
    gallery: [
        {
            id: 1,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 2,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 3,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 4,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 5,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
                {
            id: 6,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 7,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 8,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 9,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 10,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 11,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 12,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 13,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 14,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 15,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 16,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 17,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 18,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 19,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 20,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 21,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 22,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 23,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 24,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 25,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 26,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
        {
            id: 27,
            title: 'Willow',
            description: '',
            medium: 'acrylic',
            material: 'canvas',
            width: 5,
            height: 7,
            image: {
                thumbnail: '',
                small: '',
                medium: '',
                big: '',
            },
            link: {
                fb: '',
                pintrest: '',
                instagram: '',
            },
        },
    ]
}
